[package]
name = "computation-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4" }
dotenv = "0.15.0"
mongodb = "2.8.2"
serde = "1.0.199"
serde_json = "1.0.116"
